### PR TITLE
add a fall back run command for mesa supporting antique machines

### PR DESCRIPTION
**Pull request by iku000888**
Basically would make me happy from what #3 had taught me.

### CODE REVIEW

**Comment by TheFakeMontyOnTheRun** [comment]
Sorry to drop in like that, but maybe this should include a update into the README as well (`run-on-mesa`)?

**Comment by iku000888** [comment]
@TheFakeMontyOnTheRun 
Sure!

**Comment by skeeto** [comment]
Could you squash these into a single commit? If you do that I'll merge
both changes.

**Comment by iku000888** [comment]
@skeeto 
Will this do?

**Comment by skeeto** [comment]
Thanks! I made an adjustment and merged as c2373b8.

As a note for the future: remember that the first line of the commit
message should be a one-line summary of the commit. "Squashed commit of
the following:" doesn't do this. Also, since you were throwing out the
old commits, there's not really any reason to mention them. Think of a
PR as proposal composed of a series of tidy, clean patches that at least
one person will read and review. Each patch is a justifcation and a
description changes being made (commit message) attached to the precise
diff of those changes.

**Comment by iku000888** [comment]
Thanks @skeeto for the much needed guidance for the confused!

**Pull request merged**
