### PR TITLE
fixes + doc to compile on OSX

### PR DESCRIPTION
**Pull request by martinlindhe**

### CODE REVIEW

**Comment by skeeto** [comment]
Thanks for these OS X patches, especially since I don't have access to that system. A few notes:
- `M_PI` is a non-standard extension to math.h, so I'd prefer to keep it defined. Under gcc+glibc set to -std=c99, it won't be defined.
- I accidentally used labs() instead of floor(). All I really want is truncation, to detect when it's on a new second. Just changed this to a plain old cast in fcfab37. Judging from the revert you probably figured this out already.

I've cherry-picked your two OS X commits.

**Comment by martinlindhe** [comment]
cool ;) i'll try to compile it asap (ps, the osx system compiler is llvm, which wanted math.h included not for M_PI but for labs() iirc)

**Comment by skeeto** [comment]
Maybe it's different on OS X, but labs() should be from stdlib.h rather
than math.h. That's according to the C specification.

**Comment by martinlindhe** [comment]
Okays. I tried with the latest HEAD and it compiles and runs without any warnings on OSX now ;-)

Dont know how useful this is, but here's the output from before the osx fixes (llvm):

```
cc -std=c99 -O2 -Wall -Wextra -Igl3w/    demo.c gl3w/gl3w.c  -lglfw -lGL -ldl -o demo
demo.c:87:9: warning: using integer absolute value function 'labs' when argument is of floating point type
      [-Wabsolute-value]
    if (labs(now) != labs(context->lastframe)) {
        ^
demo.c:87:9: note: use function 'fabs' instead
    if (labs(now) != labs(context->lastframe)) {
        ^~~~
        fabs
demo.c:87:9: note: include the header <math.h> or explicitly provide a declaration for 'fabs'
demo.c:87:22: warning: using integer absolute value function 'labs' when argument is of floating point type
      [-Wabsolute-value]
    if (labs(now) != labs(context->lastframe)) {
                     ^
demo.c:87:22: note: use function 'fabs' instead
    if (labs(now) != labs(context->lastframe)) {
                     ^~~~
                     fabs
demo.c:87:22: note: include the header <math.h> or explicitly provide a declaration for 'fabs'
2 warnings generated.
ld: library not found for -lglfw
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [demo] Error 1
```

**Comment by skeeto** [comment]
Awesome, thanks! That was easy.

**Pull request closed without merging**
